[package]
name = "butler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
regex = "1"
shell-words = "1"
watchexec-events = "6"
tokio = { version = "1", features = ["net", "rt", "signal", "time"] }
watchexec = "8"
watchexec-signals = "5"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31", features = ["process", "signal"] }

[lints.clippy]
pedantic = {level = "deny", priority = -1}
nursery = {level = "deny", priority = -1}
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
